peft: "lora"
model_name: "allenai/OLMo-7B-Instruct"
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
save_mem: true
max_input_length: 1024
stream:
  bs: 1
  n_step_per_batch: 1

output_dir: "runs_olmo_ocl/mmlu/task_{TASK_ID}"

templates:
  task_id: "{TASK_ID}"

ocl:
  task_category: "mmlu"
  task_id: "{TASK_ID}"

exp_group: "mmlu"

mmlu:
  path: "data/mmlu/data/"
  cot_prompt_path: "data/flan-2/mmlu-cot.json"
  few_shot_k: 5

  is_cot: false
  is_few_shot: true
  answer_type: "text"
  train_split: "dev"

is_lm_sft: true

grad_accum: 16
ocl_steps: 300
max_epoch: 1000
ocl_val_step: 30

gradient_accumulation_steps: 8

mmlu_tasks:
  - abstract_algebra
  - anatomy
  - astronomy
  - business_ethics
  - clinical_knowledge
  - college_biology
  - college_chemistry
  - college_computer_science
  - college_mathematics
  - college_medicine
  - college_physics
  - computer_security
  - conceptual_physics
  - econometrics
  - electrical_engineering
  - elementary_mathematics
  - formal_logic
  - global_facts
  - high_school_biology
  - high_school_chemistry
  - high_school_computer_science
  - high_school_european_history
  - high_school_geography
  - high_school_government_and_politics
  - high_school_macroeconomics
  - high_school_mathematics
  - high_school_microeconomics
  - high_school_physics
  - high_school_psychology
  - high_school_statistics
  - high_school_us_history
  - high_school_world_history
  - human_aging
  - human_sexuality
  - international_law
  - jurisprudence
  - logical_fallacies
  - machine_learning
  - management
  - marketing
  - medical_genetics
  - miscellaneous
  - moral_disputes
  - moral_scenarios
  - nutrition
  - philosophy
  - prehistory
  - professional_accounting
  - professional_law
  - professional_medicine
  - professional_psychology
  - public_relations
  - security_studies
  - sociology
  - us_foreign_policy
  - virology
  - world_religions