peft: "lora"
model_name: "allenai/OLMo-7B-Instruct"
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
save_mem: true
max_input_length: 1024
stream:
  bs: 1
  n_step_per_batch: 1

output_dir: "runs_olmo_ocl/bbh/task_{TASK_ID}"

templates:
  task_id: "{TASK_ID}"

ocl:
  task_category: "bbh"
  task_id: "{TASK_ID}"

exp_group: "bbh"

bbh_tasks:
  - boolean_expressions
  - causal_judgement
  - date_understanding
  - disambiguation_qa
  - dyck_languages
  - formal_fallacies
  - geometric_shapes
  - hyperbaton
  - logical_deduction_five_objects
  - logical_deduction_seven_objects
  - logical_deduction_three_objects
  - movie_recommendation
  - multistep_arithmetic_two
  - navigate
  - object_counting
  - penguins_in_a_table
  - reasoning_about_colored_objects
  - ruin_names
  - salient_translation_error_detection
  - snarks
  - sports_understanding
  - temporal_sequences
  - tracking_shuffled_objects_five_objects
  - tracking_shuffled_objects_seven_objects
  - tracking_shuffled_objects_three_objects
  - web_of_lies
  - word_sorting
bbh:
  path: "data/BIG-Bench-Hard/bbh_split"
  prompt_path: "data/BIG-Bench-Hard/cot-prompts"
  is_cot: false


is_lm_sft: true

grad_accum: 16
ocl_steps: 300
max_epoch: 1000
ocl_val_step: 30

gradient_accumulation_steps: 8

